#ifdef __cplusplus
#    include <SDL2/SDL.h>
#    include <SDL2/SDL_image.h>
#    include <SDL2/SDL_mixer.h>
#    include <SDL2/SDL_render.h>
#    include <SDL2/SDL_surface.h>
#    include <SDL2/SDL_ttf.h>
#    include <boost/asio.hpp>
#    include <boost/circular_buffer.hpp>
#    include <boost/lockfree/spsc_queue.hpp>
#    include <boost/system.hpp>
#    include <boost/thread.hpp>
#    include <box2d/box2d.h>
#    include <glm/glm.hpp>
#    include <lua/lua.hpp>
#    include <msgpack/adaptor/cpp17/variant.hpp>
#    include <rapidjson/document.h>
#    include <rapidjson/error/error.h>
#    include <rapidjson/filereadstream.h>
#    include <rva/variant.hpp>
#    include <sys/signal.h>
#    include <LuaBridge/LuaBridge.h>
#    include <LuaBridge/Map.h>
#    include <LuaBridge/Optional.h>
#    include <LuaBridge/Vector.h>

#    include <algorithm>
#    include <array>
#    include <atomic>
#    include <cassert>
#    include <chrono>
#    include <csignal>
#    include <cstddef>
#    include <cstdint>
#    include <cstdio>
#    include <cstdlib>
#    include <deque>
#    include <exception>
#    include <filesystem>
#    include <functional>
#    include <iomanip>
#    include <iostream>
#    include <map>
#    include <memory>
#    include <msgpack.hpp>
#    include <optional>
#    include <set>
#    include <span>
#    include <sstream>
#    include <stdexcept>
#    include <string>
#    include <string_view>
#    include <thread>
#    include <tuple>
#    include <type_traits>
#    include <unordered_map>
#    include <utility>
#    include <variant>
#    include <vector>
#endif
